language: generic

matrix:
  include:
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=py3
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - tox # or py.test for Python versions 3.5 and below
