version: '3.3'
networks:
  seeker:
volumes:
  postgresql-data:
services:
  postgres:
    container_name: seeker_postgres
    hostname: postgres
    image: postgres:11.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - seeker
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: seeker_app
    command: sh -c "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    image: seeker_image
    hostname: app
    depends_on:
      - postgres
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    networks:
      - seeker
