version: '3.3'
networks:
  seeker:
volumes:
  postgresql-data:
services:
  postgres:
    container_name: seeker_postgres
    hostname: postgres
    image: postgres:11.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - seeker
    expose:
      - "5435"
    ports:
      - "5435:5435"
    command: -p 5435
    # restart: on-failure
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: seeker_app
    command: sh -c "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    # environment:
    #   - DJANGO_SETTINGS_MODULE=seeker.settings.local
    image: seeker_image
    hostname: app
    depends_on:
      - postgres
    expose:
      - "8001"
    ports:
      - "8001:8001"
    volumes:
      - .:/usr/src/app
    networks:
      - seeker
    # restart: on-failure
