# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist =
    py3
    flake8

[flake8]
# D100: Missing docstring in public module
# D101: Missing docstring in public class
# D102: Missing docstring in public method
# D103: Missing docstring in public function
# D105: Missing docstring in magic method
# D200: One-line docstring should fit on one line with quotes
# D202: No blank lines allowed after function docstring
# D400: First line should end with a period
# D401: First line should be in imperative mood
# E501: Line too long
# N805: First argument of a method should be named 'self'
# N806: Variable in function should be lowercase
ignore = D100,D101,D102,D103,D105,D200,D202,D400,D401,E501,N805,N806

[testenv:py3]
basepython = python3.6
deps =
    -r requirements.txt
commands =
    py.test {posargs:tests}


[testenv:flake8]
basepython=python3.6
deps=flake8>=2.2.0
commands=flake8
