# Generated by Django 2.0.5 on 2018-05-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=55)),
            ],
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['scrape_date']},
        ),
    ]
